### ISSUE TITLE
bug select day

### ISSUE THREAD

**Issue by noppon0031** [Radency/flutter_customizable_calendar#51]
https://github.com/user-attachments/assets/6c78953c-7e51-41a6-8d01-733ca51986c0

I encountered this bug after fixing the bug in version 0.3.7

**Comment by noppon0031** [comment]
help me please @AndriiVivcharenko

**Comment by nop-gkdev** [comment]
Please fix this for me.

**Comment by AndriiVivcharenko** [comment]
Hi, @noppon0031 !
Sorry for the delayed response. Please test this with the `release/0.3.8` branch. This issue should be fixed now
```yaml
flutter_customizable_calendar:
  git:
    url: git@github.com:Radency/flutter_customizable_calendar.git
    ref: release/0.3.8
```
Thanks
